services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
    - "127.0.0.1::3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
