#Vaadin Copilot Integration Runtime Properties
#Mon Mar 02 17:53:40 CET 2026
endpoint=http\://127.0.0.1\:3404/vaadin/copilot-b44ba977-17e4-491f-b752-939eb93cdc04
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
